### ISSUE TITLE
Clarify process for merging master into stable

### ISSUE THREAD

**Issue by seancolsen** [civicrm/civicrm-user-guide#146]
There was some [discussion](https://chat.civicrm.org/civicrm/pl/b77we4y9rpb15yapndwa1pat6r) today about changes made in `master` not easily making their way into `stable`. What's our process for this? Currently there appear to be [quite a few](https://github.com/civicrm/civicrm-user-guide/compare/4.7...master) changes in `master` that have yet to be ported to `stable`.

**Comment by seancolsen** [comment]
I think it's important the we address this issue. There are currently 45 commits spanning the past 10 months which have not made it into the version of the User Guide which is most prominently featured on [civicrm.org/documentation](https://civicrm.org/documentation). Can other people who have been more involved in the User Guide like @joannechester @stevekessler @nganivet and @michaelmcandrew chime in with recommendations for how to proceed?

@michaelmcandrew [said](https://chat.civicrm.org/civicrm/pl/dz79twx73jdz8cgmcdtag3nf9e): 

> we should probably call master stable

I'm wondering what exactly we should do next and who should do it. I'm happy to help, but cautious to run with this one since I have not been involved with the User Guide directly. Help??

Here's how the versions are currently [defined](https://github.com/civicrm/civicrm-docs/blob/master/app/config/books/user.yml).

```yaml
langs:
  en:
    repo: 'https://github.com/civicrm/civicrm-user-guide'
    latest: master
    stable: 4.7
    history:
      - 4.6
```

@michaelmcandrew are you suggesting we change it to the following?

```yaml
langs:
  en:
    repo: 'https://github.com/civicrm/civicrm-user-guide'
    latest: master
    stable: master
    history:
      - 4.7
      - 4.6
```

If so, then I wonder what the usefulness is of having a 4.7 branch at all. But if we delete it, then we'll  break links to `https://docs.civicrm.org/user/en/4.7/` which is currently live. If we keep the 4.7 branch then we still need a process for merging commits from master into 4.7.
